.TH BEAMVIEW 1
.SH NAME
beamview \- dual-screen PDF viewer for Beamer presentations
.SH SYNOPSIS
.B beamview
[\fIOPTIONS\fR] \fIPDF_FILE\fR
.SH DESCRIPTION
.B beamview
provides a dual-screen interface for presenting Beamer-generated PDFs with
speaker notes. It opens one window displaying slides and one showing notes, and
moves them along together.
.SH OPTIONS
.TP
.B \-h, \--help
Display this help message and exit.
.SH SEE ALSO
.BR pdfpc (1),
.BR dspdfviewer (1)
.SH AUTHOR
Chris Down
.MT chris@chrisdown.name
.ME
.SH REPORTING BUGS
Please send bug reports to
.UR https://github.com/cdown/clipmenu/issues
.UE .
